config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/users', to: 'users#index'
  get '/users/new', to: 'users#new', as: :new_user
  get '/users/:id', to: 'users#show', as: :user
  get '/users/:id/edit', to: 'users#edit', as: :edit_user
  post '/users', to: 'users#create'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'
  get '/users/:id/followers', to: 'users#followers', as: :followers
  get '/users/:id/following', to: 'users#following', as: :following

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get '/sign_up', to: 'users#new', as: :sign_up
  match '/sign_in', to: 'sessions#new', as: :sign_in, via: :get
  match '/sign_out', to: 'sessions#destroy', as: :sign_out, via: :delete

  root 'static_pages#home'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC')}
	validates :content, presence: true, length: {maximum: 140}
	validates :user_id, presence: true
	# Returns microposts from the users being followed by the given user.
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: 'User'
	belongs_to :followed, class_name: 'User'
	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microposts, dependent: :destroy
	has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
	has_many :followed_users, through: :relationships, source: :followed
	has_many :reverse_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
	has_many :followers, through: :reverse_relationships, source: :follower
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	before_create :create_remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: {minimum: 6}

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def feed
		micropost.from_users_followed_by(self)
	end

	def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

	def follow!(other_user)
		relationships.create!(followed_id: other_user.id)
	end

	def unfollow!(other_user)
		relationships.find_by(followed_id: other_user.id).destroy
	end

	private
		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :signed_in_user, only: [:create, :destroy]
	before_action :correct_user, only: :destroy

	def create
		@micropost = current_user.microposts.build(micropost_params)
		if @micropost.save
			flash[:success] = 'Micropost created'
			redirect_to root_url
		else
			render 'static_pages/home'
		end
	end

	def destroy
		@micropost.destroy
		redirect_to root_url
	end

	private 
		def micropost_params
			params.require(:micropost).permit(:content)
		end

		def correct_user
			@micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
		end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :signed_in_user

	def create
		@user = User.find(params[:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
    end
	end

	def destroy
		@user = Relationship.find(params[:id]).followed
		current_user.unfollow!(@user)
		redirect_to @user
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'Invalid email/password combination'
      render 'new'
		end
		
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		if signed_in?
			@micropost = current_user.microposts.build
			@feed_items = Micropost.all
		end
	end

	def help

	end

	def about

	end

	def contact

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy, :correct_user]
	before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
	before_action :correct_user, only: [:edit, :udpate]

	def index
		@users = User.all
	end

	def show
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = 'User account successfully created.'
			sign_in @user
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			flash[:success] = 'User account successfully updated.'
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User destroyed!"
		redirect_to users_path
	end

	def followers
		@title = 'Followers'
		@user = User.find(params[:id])
		@users = @user.followers
		render 'show_follow'
	end

	def following
		@title = 'Following'
		@user = User.find(params[:id])
		@users = @user.followed_users
		render 'show_follow'
	end

	private
		def set_user
			@user = User.find(params[:id])
		end

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		# Before filters
		def correct_user
			redirect_to(root_path) unless current_user?@user
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to sign_in_path, notice: 'Please sign in'
		end
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end

end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50, gravatar: true })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar = options[:gravatar]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: class_gravatar(gravatar))
  end

  def class_gravatar(gravatar)
  	return 'gravatar' if gravatar
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweety</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Tweety</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', home_path %></li>
        <li><%= link_to 'Help', help_path %></li>
        <% if signed_in? %>
          <li><%= link_to 'Users', users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', current_user %></li>
              <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign in', sign_in_path %></li>
        <% end %>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= (key == 'error') ? 'danger' : key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>

<footer>
  <div class="container">
    <p>Rails Tutorial by <small class="text-muted">ramz</small></p>
    <nav>
      <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
      </ul>
    </nav>
  </div>
</footer>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user%>
<div class="stats">
	<a href="<%= following_path(@user)%>"><strong><%= @user.followed_users.count%></strong> following</a>
	<a href="<%= followers_path(@user)%>"><strong><%= @user.followers.count%></strong> followers</a>
</div>

app/views/static_pages/about.html.erb
<!-- app/views/static_pages/about.html.erb -->
<p>Hello, This is about page!</p>

app/views/static_pages/contact.html.erb
<!-- app/views/static_pages/contact.html.erb -->
<p>Hello, This is contact page</p>

app/views/static_pages/help.html.erb
<!-- app/views/static_pages/help.html.erb -->
<p>Hello, this is Help page</p>

app/views/static_pages/home.html.erb
<div class="row">
	<% if signed_in? %>
	<aside class="col-md-3">
		<section class="row">
	      	<%= link_to current_user do%>
	      		<%= gravatar_for current_user %>
	      	<% end %>
	  		<b><%= current_user.name %></b>
	  		<%= link_to 'view my profile', current_user, class: 'view-profile block' %>
	  		<span class="block"><%= pluralize(current_user.microposts.count, 'micropost')%></span>
		</section>
		<section class="row">
			<%= render 'shared/stats'%>
		</section>
		<section class="row">
			<%= form_for(@micropost) do |f| %>
  			<%= render 'shared/error_messages', object: f.object %>
  			<div class="form-group">
    			<%= f.text_area :content, placeholder: "Compose new micropost...", class: 'form-control post-content' %>
  			</div>
  			<%= f.submit "Post", class: "btn btn-primary" %>
			<% end %>
		</section>
	</aside>

	<aside class="col-md-9">
		<h3 class="title-microposts">Micropost Feed</h3>
		<ul class="user-microposts">
			<% unless @feed_items.nil? %>
				<% @feed_items.each do |feed_item| %>
					<li>
						<a href="<%= user_path feed_item.user %>">
							<%= gravatar_for feed_item.user%>
						</a>
						<p><%= feed_item.content %></p>
						<small class="text-muted">Posted <%= time_ago_in_words(feed_item.created_at) %> ago.</small>
						<% if current_user?(feed_item.user) %>
    						<%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  						<% end %>
					</li>
				<% end %>
			<% end %>
		</ul>
	</aside>
	<% else %>
	<div class="jumbotron">
  		<h1>Welcome to the Tweety app</h1>
  		<p>This is the home page for <a href="http://railstutorial.org" target="_blank">Ruby on Rails</a> sample application</p>
  		<p><%= link_to 'Sign up now!', sign_up_path, class: 'btn btn-primary btn-lg', role: 'button' %></p>
	</div>
	<% end %>
	
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-6 col-md-6">
    <h2>Updating Profile</h2>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit "Update", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h2><%= pluralize(@users.count, 'User') %> Found </h2>
<div class="row" id="users">
	<% @users.each do |user| %>
	<div class="col-sm-6 col-md-2">
    <div class="thumbnail">
      <% if current_user.admin? && !current_user?(user) %>
        <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" }, class: 'user-delete' %>
      <% end %>
      <%= gravatar_for(user, size: "100%", gravatar: false) %>
      <div class="caption" style="text-align: center">
        <h4><%= user.name %></h4>
        <p>Just enjoy the show</p>
        <p><%= link_to 'View Profile', user, class: 'btn btn-link' %></p>
      </div>
    </div>
  </div>
	<% end %>
</div>
<%= link_to 'New User', new_user_path, class: 'btn btn-success' %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-6 col-md-6">
    <h2>Sign up</h2>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit "Create account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<aside class="col-md-3">
		<section class="row">
	      	<%= link_to @user do%>
	      		<%= gravatar_for @user %>
	      	<% end %>
	  		<b><%= @user.name %></b>
		</section>
		<section class="row">
			<%= render 'shared/stats'%>
		</section>
	</aside>
	<aside class="col-md-9">
		<% unless current_user?@user %>
			<% if current_user.following?@user %>
				<%= link_to 'Unfollow', relationship_path(current_user.relationships.find_by(followed_id: @user.id)), class: 'btn btn-lg btn-default', method: :delete %>
			<% else %>
				<%= link_to 'Follow', relationships_path(followed_id: @user.id), class: 'btn btn-lg btn-primary', method: :post %>
			<% end %>
		<% end %>
		<% if @user.microposts.any? %>
			<h3 class="title-microposts">Microposts (<%= @user.microposts.count%>)</h3>
			<ul class="user-microposts">
					<% @user.microposts.each do |micropost| %>
						<li>
							<p><%= micropost.content %></p>
							<small class="text-muted">Posted <%= time_ago_in_words(micropost.created_at) %> ago.</small>
							<% if current_user?(micropost.user) %>
	    						<%= link_to "delete", micropost, method: :delete,
	                                     data: { confirm: "You sure?" },
	                                     title: micropost.content %>
	  						<% end %>
						</li>
					<% end %>
			</ul>
		<% end %>
	</aside>
</div>

app/views/users/show_follow.html.erb
<div class="row">
	<aside class="col-md-3">
		<section class="row">
	      	<%= gravatar_for @user %>
	  		<b><%= @user.name %></b>
	  		<%= link_to 'view my profile', @user, class: 'view-profile block' %>
	  		<span class="block"><%= pluralize(@user.microposts.count, 'micropost')%></span>
		</section>
		<section class="row">
			<%= render 'shared/stats'%>
		</section>
	</aside>

	<aside class="col-md-9">
		<h3 class="title-microposts"><%= @title%></h3>
		<ul class="followers-following">
			<% unless @users.nil? %>
				<% @users.each do |user| %>
					<li>
						<%= gravatar_for user%>
						<%= link_to user.name, user_path(user) %>
						<p class="text-muted"><%= user.email %></p>
					</li> 
				<% end %>
			<% end %>
		</ul>
	</aside>
</div>